Repository omgnetwork/elixir-omg, pull requests merged in 2020-09, with the labels that each got.

#1708 feat: reintroduce automated changelog
  .github/workflows/enforce-changelog-labels.yml
  .github_changelog_generator
  CHANGELOG.md
  Makefile
Labels: chore

#1703 fix: block submission stall monitor should ignore block_submitting that are already mined
  apps/omg_child_chain/lib/omg_child_chain/block_queue/submission_monitor.ex
  apps/omg_child_chain/test/omg_child_chain/block_queue/submission_monitor_test.exs
Labels: bug

#1714 fix: fix in-flight exit deleted bug and add tests
  .gitmodules
  apps/omg_eth/test/omg_eth/root_chain/abi_test.exs
  apps/omg_watcher/lib/omg_watcher/exit_processor.ex
  apps/omg_watcher/test/omg_watcher/ethereum_event_aggregator_test.exs
Labels: bug

#1725 revert: reverts ife deletion commits
  .gitmodules
  apps/omg_db/lib/db.ex
  apps/omg_eth/lib/omg_eth/root_chain/abi.ex
  apps/omg_eth/lib/omg_eth/root_chain/abi_event_selector.ex
  apps/omg_eth/lib/omg_eth/root_chain/fields.ex
  apps/omg_eth/test/omg_eth/root_chain/abi_test.exs
  apps/omg_watcher/lib/omg_watcher/coordinator_setup.ex
  apps/omg_watcher/lib/omg_watcher/ethereum_event_aggregator.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
  apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
  apps/omg_watcher/test/omg_watcher/ethereum_event_aggregator_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/in_flight_exit_info_test.exs
Labels: bug

#1720 fix: set :last_ife_exit_deleted_eth_height on deplyment if it's not set yet
  Makefile
  apps/omg_db/lib/db.ex
  apps/omg_db/lib/omg_db/release_tasks/init_keys_with_values.ex
  apps/omg_db/lib/omg_db/rocksdb/server.ex
  apps/omg_db/test/omg_db/release_tasks/init_keys_with_values_test.exs
  apps/omg_eth/lib/omg_eth/root_chain/abi.ex
  apps/omg_eth/lib/omg_eth/root_chain/abi_event_selector.ex
  apps/omg_eth/lib/omg_eth/root_chain/fields.ex
  apps/omg_eth/test/omg_eth/root_chain/abi_test.exs
  apps/omg_watcher/lib/omg_watcher/coordinator_setup.ex
  apps/omg_watcher/lib/omg_watcher/ethereum_event_aggregator.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor/core.ex
  apps/omg_watcher/lib/omg_watcher/exit_processor/in_flight_exit_info.ex
  apps/omg_watcher/lib/omg_watcher/sync_supervisor.ex
  apps/omg_watcher/test/omg_watcher/ethereum_event_aggregator_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/core/state_interaction_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/core_test.exs
  apps/omg_watcher/test/omg_watcher/exit_processor/in_flight_exit_info_test.exs
Labels: bug, watcher, watcher-info

#1738 move dev env deployment job to helm repo
  .circleci/ci_deploy.sh
  .circleci/ci_increase_chart_version.sh
  .circleci/config.yml
Labels: chore

#1742 fix: handle metrics for in flight exit deleted processor
  apps/omg_status/lib/omg_status/metric/event.ex
Labels: bug

#1732 Kevsul/standard exit perf test
  priv/perf/apps/load_test/lib/child_chain/deposit.ex
  priv/perf/apps/load_test/lib/child_chain/exit.ex
  priv/perf/apps/load_test/lib/child_chain/utxos.ex
  priv/perf/apps/load_test/lib/child_chain/watcher_sync.ex
  priv/perf/apps/load_test/lib/common/byzantine_events.ex
  priv/perf/apps/load_test/lib/common/extended_perftest.ex
  priv/perf/apps/load_test/lib/common/generators.ex
  priv/perf/apps/load_test/lib/common/runner.ex
  priv/perf/apps/load_test/lib/common/sender_manager.ex
  priv/perf/apps/load_test/lib/common/sender_server.ex
  priv/perf/apps/load_test/lib/ethereum/ethereum.ex
  priv/perf/apps/load_test/lib/runner/standard_exits.ex
  priv/perf/apps/load_test/lib/scenario/many_standard_exits.ex
  priv/perf/apps/load_test/lib/scenario/start_standard_exit.ex
  priv/perf/apps/load_test/lib/scenario/watcher_status.ex
  priv/perf/apps/load_test/lib/service/faucet.ex
  priv/perf/apps/load_test/test/load_tests/common/byzantine_events_test.exs
  priv/perf/apps/load_test/test/load_tests/common/extended_perftest_test.exs
  priv/perf/apps/load_test/test/load_tests/runner/standard_exit_test.exs
  priv/perf/config/stress.exs
  priv/perf/config/test.exs
Labels: chore

#1731 update change log v1.0.4
  CHANGELOG.md
Labels: chore
