Repository omgnetwork/elixir-omg, pull requests merged in 2020-11, with the labels that each got.

#1715 feat : transaction.merge endpoint
  apps/omg_utils/lib/omg_utils/http_rpc/validators/base.ex
  apps/omg_utils/test/omg_utils/http_rpc/validators/base_test.exs
  apps/omg_watcher_info/lib/omg_watcher_info/api/transaction.ex
  apps/omg_watcher_info/lib/omg_watcher_info/db/txoutput.ex
  apps/omg_watcher_info/lib/omg_watcher_info/transaction.ex
  apps/omg_watcher_info/test/omg_watcher_info/api/transaction_test.exs
  apps/omg_watcher_info/test/omg_watcher_info/db/txoutput_test.exs
  apps/omg_watcher_info/test/omg_watcher_info/transaction_test.exs
  apps/omg_watcher_info/test/omg_watcher_info/utxo_selection_test.exs
  apps/omg_watcher_rpc/lib/web/controllers/fallback.ex
  apps/omg_watcher_rpc/lib/web/controllers/transaction.ex
  apps/omg_watcher_rpc/lib/web/router.ex
  apps/omg_watcher_rpc/lib/web/validators/merge_constraints.ex
  apps/omg_watcher_rpc/lib/web/views/transaction.ex
  apps/omg_watcher_rpc/priv/swagger/info_api_specs.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/swagger.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/paths.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/request_bodies.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/response_schemas.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/responses.yaml
  apps/omg_watcher_rpc/priv/swagger/info_api_specs/transaction/schemas.yaml
  apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
  apps/omg_watcher_rpc/test/omg_watcher_rpc/web/validators/merge_constraints_test.exs
Labels: api, enhancement

#1762 add perf cli smoke test
  .circleci/config.yml
Labels: chore

#1766 feat: send web telemetry events to Datadog
  apps/omg_status/README.md
  apps/omg_status/lib/omg_status/application.ex
  apps/omg_status/lib/omg_status/configuration.ex
  apps/omg_status/lib/omg_status/metric/telemetry.ex
  apps/omg_status/mix.exs
  apps/omg_watcher_rpc/lib/web/controllers/fallback.ex
  mix.lock
Labels: enhancement

#1768 Chore: fix feefeed container healthcheck
  .circleci/config.yml
  Makefile
  docker-compose.feefeed.yml
Labels: chore

#1772 bug: aggressive test fix
  apps/omg_watcher_info/test/omg_watcher_info/pending_block_processor_test.exs
Labels: bug

#1765 Collect metrics through datadog for the perf project
  .circleci/config.yml
  Makefile
  README.md
  docker-compose.datadog.yml
  docker-compose.dev.yml
  docker-compose.feefeed.yml
  priv/perf/Makefile
  priv/perf/apps/load_test/lib/application.ex
  priv/perf/apps/load_test/lib/child_chain/transaction.ex
  priv/perf/apps/load_test/lib/runner/transactions.ex
  priv/perf/apps/load_test/lib/runner/utxos.ex
  priv/perf/apps/load_test/lib/scenario/deposits.ex
  priv/perf/apps/load_test/lib/scenario/transactions.ex
  priv/perf/apps/load_test/lib/service/datadog.ex
  priv/perf/apps/load_test/lib/service/datadog/api.ex
  priv/perf/apps/load_test/lib/service/datadog/dummy_statix.ex
  priv/perf/apps/load_test/lib/service/metrics.ex
  priv/perf/apps/load_test/lib/test_runner.ex
  priv/perf/apps/load_test/lib/test_runner/config.ex
  priv/perf/apps/load_test/lib/test_runner/help.ex
  priv/perf/apps/load_test/lib/watcher_info/balance.ex
  priv/perf/apps/load_test/lib/watcher_info/client.ex
  priv/perf/apps/load_test/lib/watcher_info/transaction.ex
  priv/perf/apps/load_test/lib/watcher_info/utxo.ex
  priv/perf/apps/load_test/mix.exs
  priv/perf/apps/load_test/test/load_test/runner/childchain_test.exs
  priv/perf/apps/load_test/test/load_test/runner/smoke_test.exs
  priv/perf/apps/load_test/test/load_test/runner/standard_exit_test.exs
  priv/perf/apps/load_test/test/load_test/runner/utxos_load_test.exs
  priv/perf/apps/load_test/test/load_test/runner/watcher_info_test.exs
  priv/perf/apps/load_test/test/load_test/service/datadog/api_test.exs
  priv/perf/apps/load_test/test/load_tests/runner/deposits_test.exs
  priv/perf/apps/load_test/test/test_helper.exs
  priv/perf/config/config.exs
  priv/perf/config/test.exs
  priv/perf/mix.exs
  priv/perf/mix.lock
Labels: chore

#1774 retry datadog errors
  priv/perf/apps/load_test/lib/service/datadog/api.ex
Labels: chore

#1775 ignore known errors - Sentry spike protection
  .circleci/config.yml
  Makefile
  apps/omg_status/lib/omg_status/sentry_filter.ex
  apps/omg_status/mix.exs
  apps/omg_watcher_rpc/lib/web/endpoint.ex
  mix.lock
Labels: enhancement

#1773 Fix readme docker docs
  Makefile
  README.md
  config/test.exs
  docker-compose.dev.yml
  docker/create_databases.sql
  priv/perf/README.md
Labels: chore

#1778 config filter sentry
  config/config.exs
Labels: bug

#1781 extract geth command, remove childchain only code paths
  .circleci/config.yml
  README.md
  apps/omg/lib/omg/state.ex
  apps/omg/lib/omg/state/core.ex
  apps/omg/lib/omg/state/transaction/fee.ex
  apps/omg/test/omg/state/core_test.exs
  apps/omg/test/omg/state/persistence_test.exs
  apps/omg/test/omg/state/transaction/fee_test.exs
  apps/omg/test/omg/state_test.exs
  apps/omg_status/lib/omg_status/monitor/statsd_monitor.ex
  apps/omg_watcher_info/lib/omg_watcher_info/release_tasks/set_db.ex
  apps/omg_watcher_info/test/omg_watcher_info/release_tasks/set_db_test.exs
  config/releases.exs
  docker-compose.yml
  docker/geth/command
  docker/geth/geth-blank-password
  mix.exs
  mix.lock
Labels: chore

#1779 Add RequestTooLarge to Sentry filter
  apps/omg_status/lib/omg_status/sentry_filter.ex
Labels: api, chore

#1679 set remote_ip from cf-connecting-ip header
  apps/omg_utils/lib/omg_utils/remote_ip.ex
  apps/omg_utils/test/omg_utils/remote_ip_test.exs
  apps/omg_watcher_rpc/lib/web/endpoint.ex
  apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/alarm_test.exs
Labels: chore

#1783 Ignoring 406 status code invalid header exception
  apps/omg_status/lib/omg_status/sentry_filter.ex
  apps/omg_status/test/sentry_filter_test.exs
Labels: bug

#1786 fix: set service name as a tag in metrics
  apps/omg_status/lib/omg_status/metric/telemetry.ex
Labels: chore

#1782 fix: limit matching for ethereumex responses
  apps/omg_eth/lib/omg_eth/client.ex
  apps/omg_eth/test/omg_eth/client_test.exs
  apps/omg_status/lib/omg_status/sentry_filter.ex
Labels: bug

#1784 Use WARN instead of ERROR on Watcher Supervisor logging
  apps/omg_watcher/lib/omg_watcher/ethereum_event_aggregator.ex
  apps/omg_watcher/lib/omg_watcher/monitor.ex
Labels: chore
