Repository omgnetwork/elixir-omg, pull requests merged in 2020-10, with the labels that each got.

#1743 Chore: use exexec from upstream
  apps/omg_eth/mix.exs
  apps/omg_eth/test/support/dev_geth.ex
  apps/omg_eth/test/support/dev_node.ex
  mix.lock
Labels: chore

#1748 fix: recheck PR label on synchronize and reopen
  .github/workflows/enforce-changelog-labels.yml
Labels: bug

#1745 deposits performance tests bot
  apps/omg_eth/test/support/dev_geth.ex
  docker-compose.feefeed.yml
  priv/perf/apps/load_test/lib/child_chain/deposit.ex
  priv/perf/apps/load_test/lib/child_chain/exit.ex
  priv/perf/apps/load_test/lib/child_chain/transaction.ex
  priv/perf/apps/load_test/lib/child_chain/utxos.ex
  priv/perf/apps/load_test/lib/child_chain/watcher_sync.ex
  priv/perf/apps/load_test/lib/ethereum/ethereum.ex
  priv/perf/apps/load_test/lib/runner/deposits.ex
  priv/perf/apps/load_test/lib/scenario/deposits.ex
  priv/perf/apps/load_test/lib/service/faucet.ex
  priv/perf/apps/load_test/lib/service/sleeper.ex
  priv/perf/apps/load_test/lib/service/sync.ex
  priv/perf/apps/load_test/lib/test_runner.ex
  priv/perf/apps/load_test/lib/test_runner/config.ex
  priv/perf/apps/load_test/lib/watcher_info/balance.ex
  priv/perf/apps/load_test/lib/watcher_info/transaction.ex
  priv/perf/apps/load_test/mix.exs
  priv/perf/apps/load_test/test/load_tests/runner/deposits_test.exs
  priv/perf/config/config.exs
  priv/perf/mix.lock
Labels: enhancement

#1683 feat: transaction.create optimisation
  .gitignore
  apps/omg_watcher_info/lib/omg_watcher_info/api/transaction.ex
  apps/omg_watcher_info/lib/omg_watcher_info/db/txoutput.ex
  apps/omg_watcher_info/lib/omg_watcher_info/order_fee_fetcher.ex
  apps/omg_watcher_info/lib/omg_watcher_info/transaction.ex
  apps/omg_watcher_info/lib/omg_watcher_info/utxo_selection.ex
  apps/omg_watcher_info/test/omg_watcher_info/db/txoutput_test.exs
  apps/omg_watcher_info/test/omg_watcher_info/transaction_test.exs
  apps/omg_watcher_info/test/omg_watcher_info/utxo_selection_test.exs
  apps/omg_watcher_rpc/lib/web/controllers/fallback.ex
  apps/omg_watcher_rpc/lib/web/controllers/transaction.ex
  apps/omg_watcher_rpc/lib/web/validators/order.ex
  apps/omg_watcher_rpc/test/omg_watcher_rpc/web/controllers/transaction_test.exs
Labels: chore, watcher-info

#1751 chore: bump version to 1.0.4
  VERSION
Labels: chore

#1754 feat: comply with new Infura API
  .circleci/config.yml
  Makefile
  apps/omg_conformance/test/support/conformance/merkle_proofs.ex
  apps/omg_conformance/test/support/conformance/signatures_hashes.ex
  apps/omg_eth/lib/omg_eth/root_chain/rpc.ex
  apps/omg_eth/test/fixtures.exs
  priv/perf/apps/load_test/lib/child_chain/exit.ex
  priv/perf/apps/load_test/lib/ethereum/ethereum.ex
Labels: enhancement

#1747 chore: changelog/version bump for v1.0.5
  CHANGELOG.md
  VERSION
Labels: chore

#1753 Publish the perf project
  .circleci/config.yml
  Makefile
  apps/omg_eth/test/support/dev_geth.ex
  priv/perf/Dockerfile
Labels: chore

#1756 Utxo perf test
  priv/perf/apps/load_test/lib/runner/utxos.ex
  priv/perf/apps/load_test/lib/scenario/deposits.ex
  priv/perf/apps/load_test/lib/scenario/utxos.ex
  priv/perf/apps/load_test/lib/test_runner/config.ex
  priv/perf/apps/load_test/lib/watcher_info/balance.ex
  priv/perf/apps/load_test/lib/watcher_info/utxo.ex
  priv/perf/apps/load_test/test/load_tests/runner/utxos_test.exs
  priv/perf/config/config.exs
Labels: enhancement

#1757 Add cli help command for the perf project
  priv/perf/apps/load_test/lib/test_runner.ex
  priv/perf/apps/load_test/lib/test_runner/config.ex
  priv/perf/apps/load_test/lib/test_runner/help.ex
Labels: chore
